version: '3'

networks:
  default:
    external: true
    name: evebot_services

services:
  evebot:
    image: evebot/app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.compose
    environment:
      ENTRY_APP: server
    ports:
      - 8000:8000
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"

  evebot-celery-beat:
    image: evebot/app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.compose
    environment:
      ENTRY_APP: beat
    depends_on:
      - evebot
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"

  evebot-celery-worker:
    image: evebot/app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.compose
    environment:
      ENTRY_APP: worker
    depends_on:
      - evebot
      - evebot-celery-beat
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"

  evebot-celery-worker-universe:
    image: evebot/app
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A evebot worker -l info -P eventlet -c 100 -Q universe
    env_file:
      - .env.compose
    depends_on:
      - evebot
      - evebot-celery-beat
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"

  evebot-celery-worker-realtime:
    image: evebot/app
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A evebot worker -l info -P eventlet -c 100 -Q realtime
    env_file:
      - .env.compose
    depends_on:
      - evebot
      - evebot-celery-beat
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"

  evebot-celery-flower:
    image: evebot/app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.compose
    environment:
      ENTRY_APP: flower
    depends_on:
      - evebot
      - evebot-celery-beat
      - evebot-celery-worker
      - evebot-celery-worker-universe
      - evebot-celery-worker-realtime
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"