version: '3'

networks:
  default:
    external: true
    name: evebot_services

services:
  evebot:
    image: evebot/app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.compose
    environment:
      ENTRY_APP: server
    ports:
      - 8000:8000
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"

  evebot-celery-beat:
    image: evebot/app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.compose
    environment:
      ENTRY_APP: beat
    depends_on:
      - evebot
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"


  evebot-celery-worker:
    image: evebot/app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.compose
    environment:
      ENTRY_APP: worker
    depends_on:
      - evebot
      - evebot-celery-beat
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"
